-- First, remove the table if it exists
drop table if exists bookmarks;

-- Create the table anew
create table bookmarks (
    id INTEGER primary key generated by default as identity,
    title varchar(25),
    url TEXT NOT NULL,
    description TEXT,
    rating INTEGER CHECK(rating BETWEEN 1 AND 5)
);

-- insert some test data
-- Using a multi-row insert statement here
insert into bookmarks (title, url, description, rating)
values
('Bookmark 1', 'www.bookmark1.com', 'Bookmark 1!', 3),
('Bookmark 2', 'www.bookmark2.com', 'Bookmark 2!', 2),
('Bookmark 3', 'www.bookmark3.com', 'Bookmark 3!', 3),
('Bookmark 4', 'www.bookmark4.com', null, null),
('Bookmark 5', 'www.bookmark5.com', 'A description about bookmark 5', 1),
('Bookmark 6', 'www.bookmark6.com', null, 3),
('Bookmark 7', 'www.bookmark7.com', 'This is bookmark 7', null),
('Bookmark 8', 'www.bookmark8.com', null, 1),
('Bookmark 9', 'www.bookmark9.com', 'This is bookmark 9', 1),
('Bookmark 10', 'www.bookmark10.com', 'Best bookmark ever!', 5)